name: UltimateChat
main: br.net.fabiozumbi12.UltimateChat.UChat
version: ${project.version}
author: FabioZumbi12
description: ${project.description}
softdepend: [mcMMO, SkillAPI, Essentials, SimpleClans, Vault, MarriageMaster, Marriage, PlaceholderAPI, Factions]
commands:
  uchat:
    description: "Main command for ${project.name}."
    aliases: [uchat, chat]
  channel:
    description: "Channel commands"
  tell:
    description: "Tell command"
  ubroadcast:
    description: "Broadcast command"
  umsg:
    description: "Send a message to player"
permissions:
  uchat.*:
    description: "All ultimatechat commands."
    default: op
    children:
      uchat.admin: true
      uchat.player: true
  uchat.admin:
    description: "All admin commands."
    default: false
    children:
      uchat.cmd.reload: true
      uchat.cmd.spy: true
      uchat.cmd.mute: true
      uchat.cmd.umsg: true
      uchat.chat.mention: true
      uchat.chat.color: true
      uchat.chat.color.formats: true
      uchat.chat.color.magic: true
      uchat.cmd.clear-all: true
      uchat.channel.admin: true
      uchat.broadcast: true      
      uchat.bypass.cost: true
      uchat.bypass-anti-ip: true
      uchat.bypass-spam: true
  uchat.player:
    description: "All player commands."
    default: true
    children:
      uchat.cmd.ignore.player: true
      uchat.cmd.ignore.channel: true
      uchat.cmd.tell: true
      uchat.cmd.clear: true
      uchat.chat.click-urls: true
      uchat.channel.global: true
      uchat.channel.local: true
  uchat.bypass-protections:
    description: "Permissions to bypass chat checks."
    default: false
    children:
      uchat.bypass-spam: true
      uchat.bypass-censor: true
      uchat.bypass-anti-ip: true
      uchat.bypass-enhancement: true